### PR TITLE
Added german language

### PR DESCRIPTION
**Pull request by mapulu**
Added german language.
Hope everything is okay. 
"athom app validate" said Homey App validated successfully against level `debug`

### CODE REVIEW

**Comment by TedTolboom** [comment]
@mapulu great initiative! Thanks for your contribution.

I see you made the changes in the app.json file.

Since this app, and many bigger apps, use a composer function (source files are located in the /drivers/ and /config/ folders with the next composition, the translations would be overwritten....
So I will need to move the translations towards the source files. 

Since it is limited to a few, I will do it with updating the changelog etc.

Once more, thanks for your contribution!

**Comment by mapulu** [comment]
ah okay
didn't know that. Next time I will use the right files.

**Comment by TedTolboom** [comment]
already fixed...
Which name and mail adress can I add as contributor?

**Comment by mapulu** [comment]
Martin Pussamsies
martin@pussamsies.de

**Pull request merged**
